# CHAPTER 3 - THE NUMPY LIBRARY

## The NumPy Installation

In [2]:
import numpy as np

## Ndarray: The Heart of the Library

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int32')

In [6]:
a.ndim

1

In [7]:
a.size

3

In [8]:
a.shape

(3,)

In [9]:
b = np.array([[1.3, 2.4], [0.3, 4.1]])
b.dtype

dtype('float64')

In [10]:
b.ndim

2

In [11]:
b.size

4

In [12]:
b.shape

(2, 2)

In [13]:
b.itemsize

8

In [14]:
b.data

### Create an Array

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
d = np.array(((1, 2, 3), (4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Types of data

In [18]:
g = np.array([['a', 'b'], ['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']],
      dtype='<U1')

In [19]:
g.dtype

dtype('<U1')

In [20]:
g.dtype.name

'str32'

### The dtype Option

In [21]:
f = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
f

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j]])

### Intrinsic Creation of an Array 

In [22]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [27]:
np.arange(0, 6, 0.6)

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4])

In [28]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.linspace(0, 10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [30]:
np.random.random(3)

array([ 0.18282316,  0.08728349,  0.55368402])

In [31]:
np.random.random((3, 3))

array([[ 0.30950094,  0.41719387,  0.64516388],
       [ 0.65969564,  0.13503792,  0.11197373],
       [ 0.5236992 ,  0.50867565,  0.14855822]])

## Basic Operations

### Arithmetic Operators

In [32]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [33]:
a + 4

array([4, 5, 6, 7])

In [34]:
a * 2

array([0, 2, 4, 6])

In [35]:
b = np.arange(4, 8)
b

array([4, 5, 6, 7])

In [36]:
a + b

array([ 4,  6,  8, 10])

In [37]:
a * b

array([ 0,  5, 12, 21])

In [38]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [39]:
a * np.sqrt(b)

array([ 0.        ,  2.23606798,  4.89897949,  7.93725393])

In [40]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
B = np.ones((3, 3))
B

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [42]:
A * B

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

### The Matrix Product

In [43]:
np.dot(A, B)

array([[  3.,   3.,   3.],
       [ 12.,  12.,  12.],
       [ 21.,  21.,  21.]])

In [44]:
A.dot(B)

array([[  3.,   3.,   3.],
       [ 12.,  12.,  12.],
       [ 21.,  21.,  21.]])

In [45]:
np.dot(B, A)

array([[  9.,  12.,  15.],
       [  9.,  12.,  15.],
       [  9.,  12.,  15.]])

### Increment and Decrement Operators

In [46]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [47]:
a += 1
a

array([1, 2, 3, 4])

In [48]:
a -= 1
a

array([0, 1, 2, 3])

In [49]:
a = np.arange(4)
a += 4
a

array([4, 5, 6, 7])

In [50]:
a *= 2
a

array([ 8, 10, 12, 14])

#### Universal Functions (ufunc)

In [51]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [52]:
np.sqrt(a)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [53]:
np.log(a)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

In [54]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Aggregate Functions

In [55]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a

array([ 3.3,  4.5,  1.2,  5.7,  0.3])

In [56]:
a.sum()

15.0

In [57]:
a.min()

0.29999999999999999

In [58]:
a.max()

5.7000000000000002

In [59]:
a.mean()

3.0

In [60]:
a.std()

2.0079840636817816

## Indexing, Slicing and Iterating

### Indexing

In [61]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [62]:
a[4]

14

In [63]:
a[-1]

15

In [64]:
a[-6]

10

In [65]:
a[[1, 3, 4]]

array([11, 13, 14])

In [66]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [67]:
A[1, 2]

15

### Slicing

In [68]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [69]:
a[1:5]

array([11, 12, 13, 14])

In [70]:
a[1:5:2]

array([11, 13])

In [71]:
a[::2]

array([10, 12, 14])

In [72]:
a[:5:2]

array([10, 12, 14])

In [73]:
a[:5:]

array([10, 11, 12, 13, 14])

In [74]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [75]:
A[0, :]

array([10, 11, 12])

In [76]:
A[:, 0]

array([10, 13, 16])

In [77]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [78]:
A[[0, 2], 0:2]

array([[10, 11],
       [16, 17]])

### Iterating an Array 

In [79]:
for i in a:
    print(i)

10
11
12
13
14
15


In [80]:
for row in A:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [81]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


In [82]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([ 13.,  14.,  15.])

In [83]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([ 11.,  14.,  17.])

In [84]:
def foo(x):
    return x/2

In [85]:
np.apply_along_axis(foo, axis=1, arr=A)

array([[ 5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ]])

In [86]:
np.apply_along_axis(foo, axis=0, arr=A)

array([[ 5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ]])

## Conditions and Boolean Arrays

In [87]:
A = np.random.random((4, 4))
A

array([[ 0.672678  ,  0.52486734,  0.55714297,  0.58869215],
       [ 0.77221479,  0.14984155,  0.25153467,  0.79623807],
       [ 0.00768109,  0.10777896,  0.3182329 ,  0.33289202],
       [ 0.94520161,  0.03784329,  0.49335599,  0.25306501]])

In [88]:
A < 0.5

array([[False, False, False, False],
       [False,  True,  True, False],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]], dtype=bool)

In [89]:
A[A < 0.5]

array([ 0.14984155,  0.25153467,  0.00768109,  0.10777896,  0.3182329 ,
        0.33289202,  0.03784329,  0.49335599,  0.25306501])

## Shape Manipulation

In [90]:
a = np.random.random(12)
a

array([ 0.34097294,  0.64751943,  0.28206463,  0.55451378,  0.41799299,
        0.13659622,  0.02457168,  0.88553069,  0.58144125,  0.98254068,
        0.54464648,  0.67442772])

In [91]:
A = a.reshape(3,4)
A

array([[ 0.34097294,  0.64751943,  0.28206463,  0.55451378],
       [ 0.41799299,  0.13659622,  0.02457168,  0.88553069],
       [ 0.58144125,  0.98254068,  0.54464648,  0.67442772]])

In [92]:
a.shape = (3, 4)
a

array([[ 0.34097294,  0.64751943,  0.28206463,  0.55451378],
       [ 0.41799299,  0.13659622,  0.02457168,  0.88553069],
       [ 0.58144125,  0.98254068,  0.54464648,  0.67442772]])

In [93]:
a = a.ravel()
a

array([ 0.34097294,  0.64751943,  0.28206463,  0.55451378,  0.41799299,
        0.13659622,  0.02457168,  0.88553069,  0.58144125,  0.98254068,
        0.54464648,  0.67442772])

In [94]:
a.shape = (12)
a

array([ 0.34097294,  0.64751943,  0.28206463,  0.55451378,  0.41799299,
        0.13659622,  0.02457168,  0.88553069,  0.58144125,  0.98254068,
        0.54464648,  0.67442772])

In [95]:
A.transpose()

array([[ 0.34097294,  0.41799299,  0.58144125],
       [ 0.64751943,  0.13659622,  0.98254068],
       [ 0.28206463,  0.02457168,  0.54464648],
       [ 0.55451378,  0.88553069,  0.67442772]])

## Array Manipulation

### Joining Arrays

In [96]:
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A, B))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [97]:
np.hstack((A, B))

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.]])

In [98]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [99]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Splitting Arrays

In [100]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
[B, C] = np.hsplit(A, 2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [102]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [103]:
[B, C] = np.vsplit(A, 2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [104]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
[A1, A2, A3] = np.split(A, [1,3], axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [106]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [107]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [108]:
[A1, A2, A3] = np.split(A, [1, 3], axis=0)
A1

array([[0, 1, 2, 3]])

In [109]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
A3

array([[12, 13, 14, 15]])

## General Concepts

### Copies or Views of Objects

In [111]:
a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [112]:
a[2] = 0
b

array([1, 2, 0, 4])

In [113]:
c = a[0:2]
c

array([1, 2])

In [114]:
a[0] = 0
c

array([0, 2])

In [115]:
a = np.array([1, 2, 3, 4])
c = a.copy()
c

array([1, 2, 3, 4])

In [116]:
a[0] = 0
c

array([1, 2, 3, 4])

### Broadcasting

In [117]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
b

array([0, 1, 2, 3])

In [119]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [120]:
m = np.arange(6).reshape(3, 1, 2)
n = np.arange(6).reshape(3, 2, 1)
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [121]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [122]:
m + n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [123]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j),
                      (3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))
structured

array([(1, b'First',  0.5       ,  1.+2.j),
       (2, b'Second',  1.29999995,  2.-2.j),
       (3, b'Third',  0.80000001,  1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [124]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j),
                      (3, 'Third', 0.8, 1+3j)],dtype=('int16, a6, float32, complex64'))
structured

array([(1, b'First',  0.5       ,  1.+2.j),
       (2, b'Second',  1.29999995,  2.-2.j),
       (3, b'Third',  0.80000001,  1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [125]:
structured['f1']

array([b'First', b'Second', b'Third'],
      dtype='|S6')

In [126]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j),(3, 'Third', 0.8, 1+3j)],
                      dtype=[('id', 'i2'),('position','a6'),('value','f4'),('complex','c8')])
structured

array([(1, b'First',  0.5       ,  1.+2.j),
       (2, b'Second',  1.29999995,  2.-2.j),
       (3, b'Third',  0.80000001,  1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [127]:
structured.dtype.names = ('id','order','value','complex')

In [128]:
structured['order']

array([b'First', b'Second', b'Third'],
      dtype='|S6')

## Reading and Writing Array Data on Files

### Loading and Saving Data in Binary Files

In [129]:
data = np.random.random(12)
data = data.reshape(4,3)
data

array([[ 0.137731  ,  0.11815342,  0.42145734],
       [ 0.26470402,  0.5018455 ,  0.26306521],
       [ 0.3239534 ,  0.76733217,  0.43839321],
       [ 0.7230763 ,  0.05229475,  0.99609402]])

In [130]:
np.save('saved_data', data)

In [131]:
loaded_data = np.load('saved_data.npy')
loaded_data

array([[ 0.137731  ,  0.11815342,  0.42145734],
       [ 0.26470402,  0.5018455 ,  0.26306521],
       [ 0.3239534 ,  0.76733217,  0.43839321],
       [ 0.7230763 ,  0.05229475,  0.99609402]])

### Reading File with Tabular Data 

In [132]:
data = np.genfromtxt('ch3_data.csv', delimiter=',', names=True)
data

array([( 1.,  123.,  1.4,  23.), ( 2.,  110.,  0.5,  18.),
       ( 3.,  164.,  2.1,  19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value2_1', '<f8')])

In [133]:
data2 = np.genfromtxt('ch3_data2.csv', delimiter=',', names=True)
data2

array([( 1.,  123.,  1.4,  23.), ( 2.,  110.,  nan,  18.),
       ( 3.,   nan,  2.1,  19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value2_1', '<f8')])

In [153]:
data2['id']

array([ 1.,  2.,  3.])

In [154]:
data2[0]

( 1.,  123.,  1.4,  23.)